### ISSUE TITLE
Visual Range Issue

### ISSUE THREAD

**Issue by CEDSS** [ChrisPJohn/SolastaCommunityExpansion#103]
In-game, there's an issue where there's weapons with "Close Range" and "Max Range" values, and an entire Long Range mechanic that was implemented in Solasta, but is currently inaccessible due to what might be a bug involving "Normal Vision Sense Range".

First, an image to show a weapon with "Close Range" and "Max Range":
![Limited Range of Vision 7](https://user-images.githubusercontent.com/43633721/142275663-42e75221-8470-4341-afd8-54f185414af5.png)

Now the problem: if you try to use these weapons at those range values, you'll get an error saying "This target is too far away to be perceived".

Just to clarify, this doesn't seem to be an issue with lighting, because you'd imagine that you would be able to see somebody under the brightness of sunlight regardless of how far away they are, but not inside a dark cave, but this problem seems to be there regardless of location or lighting. I tested everything in an early encounter, outside, under bright sunlight, with player characters that have both normal vision and darkvision.

And the solution: I added these 2 lines of code to a Sorcerer C# class in Level 20 (Random, I know, I was just testing things, it should work anywhere else)
```
using static SolastaModApi.DatabaseHelper.FeatureDefinitionSenses;
...
code
...
SenseNormalVision.SetSenseRange(120);
```

Having added those 2 lines of code, it worked. Even characters with Darkvision were able to use Long Range mechanics normally, so far I've only tested this under sunlight, I don't know what happens in very dark environments.

I added the number "120" because I assume it means 120 "cubes", which is the max range of the longbow, and I'm not sure if there's anything in the game that goes beyond this range. I tried much larger values, but they caused the game to freeze at the start of battles, so would not recommend.

This is the result:
![Limited Range of Vision 6](https://user-images.githubusercontent.com/43633721/142276089-4fa6ca4b-1af7-47bc-af2c-c0b69bf1bcfd.png)

It doesn't seem to do anything to the Fog of War, so you have to clear that up normally before you enjoy the benefits of this small change.

I'm pretty sure this mod wouldn't break any D&D 5e rules, and I'm basing my change on the Dungeon Master's Guide, chapter 8, page 243, which reads:

> Visibility Outdoors
> When traveling outdoors, characters can see about 2 miles in any direction on a clear day, or until the point where trees, hills, or other obstructions block their view. Rain normally cuts maximum visibility down to 1 mile, and fog can cut it down to between 100 and 300 feet.

120 "5ft cubes" in any 1 direction equate 600 feet, which is within reason, given the D&D 5e ruleset and the game's engine limitations, map sizes, etc.

I added this for my own enjoyment, and am still testing, but thought it would be nice to have it out there for other people to enjoy as well.

**Comment by ChrisPJohn** [comment]
Is this done now?

**Comment by CEDSS** [comment]
Yes, this feature should be on one the latest Dev commits. I'll close this issue now.
