### ISSUE TITLE
Option to force all items to refresh in merchant inventories

### ISSUE THREAD

**Issue by ChrisPJohn** [ChrisPJohn/SolastaCommunityExpansion#118]
tehcrash2

Do you take feature requests? Halman Summer doesn't seem to replenish their inventory of magical items and I really want to equip slippers of spider climbing on everyone so an option to refresh vendor's inventory would be great!

**Comment by ThyWoof** [comment]
I believe new item options features from @Silvergriffon covers that. Please confirm Silver.

**Comment by Silvergriffon** [comment]
Yes, the merchant options should make everything except for the ability score Tome/Manuals restock over time in the faction stores.

**Comment by ThyWoof** [comment]
Thanks for confirming. Closing this as we now have restocks at 1.2.15.3
