### ISSUE TITLE
Missing Reference ModKit

### ISSUE THREAD

**Issue by CEDSS** [ChrisPJohn/SolastaCommunityExpansion#134]
I've been unable to compile the latest release due to a missing assembly reference: ModKit.
![ModKit](https://user-images.githubusercontent.com/43633721/142871035-78c5c31f-2e97-4c18-932d-32e35d5acef1.png)

The assembly dependency doesn't seem to reference anything in its properties.
![ModKit0](https://user-images.githubusercontent.com/43633721/142871650-d92ab8c8-1053-4472-b19f-5e72001c5787.png)

How do I solve this?

**Comment by PhilPJL** [comment]
If you're building against the release version of ModApi which doesn't reference ModKit you need to remove

		<Reference Include="ModKit">
			<HintPath>$([System.IO.Path]::Combine($(SolastaInstallDir), 'Mods\SolastaModApi\ModKit.dll'))</HintPath>
			<Private>False</Private>
		</Reference>

from CE .csproj.

**Comment by CEDSS** [comment]
Removing the ModKit reference does get rid of the initial warning, but then it gives me errors such as these:
![ModKit1](https://user-images.githubusercontent.com/43633721/142882502-8d419588-dd80-4487-ba77-714dc436a548.png)

I tried compiling both the main and the dev branch of the SolastaModApi in GitHub to see if it would work then, but I got this error while trying to compile those:
![ModKit2](https://user-images.githubusercontent.com/43633721/142882968-2372a043-007e-4daa-8da0-5dce86d5adb5.png)

**Comment by ThyWoof** [comment]
I just pushed a new ModKit integration branch on ModApi. Try to compile and use that one. Please share results.

**Comment by ThyWoof** [comment]
I’m using game version 1.2.14 so most likely it won’t compile against 1.2.12

**Comment by CEDSS** [comment]
My bad, updating solasta to the latest beta branch hotfix, then compiling mod api, then compiling CE without deleting anything worked
