### ISSUE TITLE
Conjure Elemental should be up-castable

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#231]
Per SRD description of Conjure Elemental

_When you cast this spell using a spell slot of 6th level or higher, the CR increases by 1 for each slot level above 5th._

**Comment by ChrisPJohn** [comment]
This would require replacing the effect of the spell with a custom effect form (https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/293/files), but I think we can do this.

The spell slot level being used to cast the spell is stored in ApplyFormsParams.effectLevel

**Comment by PhilPJL** [comment]
Closed by PR.
