### ISSUE TITLE
Select an item screen filter improvement

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#241]
The select an item screen doesn't search the title of the item.  e.g.

![image](https://user-images.githubusercontent.com/271656/146436697-2029e69a-07de-442e-bc63-b2efb86fed11.png)

But of course there are diamonds

![image](https://user-images.githubusercontent.com/271656/146436833-c98250ce-e4aa-48e3-afe3-5036de3d9841.png)

etc.  Annoying.

**Comment by ThyWoof** [comment]
class ItemFilteringGroup. Refresh() method.

`  public void Refresh(bool notify = true)
  {
    if (this.itemsList == null)
      return;
    this.refreshing = true;
    this.filteredItemsList.Clear();
    for (int index = 0; index < this.itemsList.Count; ++index)
    {
      ItemDefinition items = this.itemsList[index];
      GuiItemDefinition guiItemDefinition = this.guiItemDefinitions[index];
      if ((string.IsNullOrEmpty(this.keyword) || guiItemDefinition.Title.IndexOf(this.keyword, StringComparison.OrdinalIgnoreCase) > 0) && (this.showCustom || !items.UserItem))
      {
        if (this.currentCategory == "All")
          this.filteredItemsList.Add(items);
        else if (this.currentCategory == "Custom" && items.UserItem)
          this.filteredItemsList.Add(items);
        else if (items.MerchantCategory == this.currentCategory)
          this.filteredItemsList.Add(items);
      }
    }
    if (notify)
    {
      ItemFilteringGroup.ItemsFilteredHandler itemsFiltered = this.ItemsFiltered;
      if (itemsFiltered != null)
        itemsFiltered(this.filteredItemsList);
    }
    this.refreshing = false;
  }`

**Comment by PhilPJL** [comment]
Yep, needs to search translated title not title.

**Comment by PhilPJL** [comment]
Bug for TA to fix I think
