### ISSUE TITLE
Out game level up screen improvement

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#243]
When levelling up a character out of game it's annoying that the screen is closed on [Finish] is you want to level up several times.  Add a button [Next Level] to take us straight into defining the next level.

![image](https://user-images.githubusercontent.com/271656/146441010-6d2b7c59-6cb4-4b69-b31e-dcf6660c3ff8.png)

**Comment by RedOrcaCode** [comment]
This would be a huge QoL improvement.

**Comment by ThyWoof** [comment]
Will do it

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/146475875-049d4f61-76a2-4aec-978d-350f8fb20f8a.png)
;-)

**Comment by ThyWoof** [comment]
https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/252/files
