### ISSUE TITLE
6 character party and zone exits

### ISSUE THREAD

**Issue by EnderWiggin** [ChrisPJohn/SolastaCommunityExpansion#300]
I've tried 6 man party size and noticed that custom campaigns generally have zone change area that fits only 4 characters. Is it possible to modify how this zone detects characters to allow progression even if not all characters are on it?

**Comment by ThyWoof** [comment]
I’ve tried that but it can break the game. A workaround is to pause the game, individually select each hero towards one of the 4 squares and unpause. That should be enough to trigger the gadget.

**Comment by ThyWoof** [comment]
Will add this tip to mod UI.

**Comment by ThyWoof** [comment]
closing this one as already tried a fix before that proven worse than the workaround.
