### ISSUE TITLE
Hard locked doors with custom item keys broken, cannot open

### ISSUE THREAD

**Issue by vel8b8** [ChrisPJohn/SolastaCommunityExpansion#312]
When CE is enabled, hard locked doors that use a custom item as a key cannot be opened because the key item disappears from the door. 

This is rather bad as it blocks player progress.

I tested this with a clean install with no mods and a separate install with only SolastaModApi and CE. Toggling off CE and restarting Solasta fixes the issue, so it's a CE bug.

Attached a repro campaign.

[TestHardLockDoors.zip](https://github.com/ChrisPJohn/SolastaCommunityExpansion/files/7783171/TestHardLockDoors.zip)

**Comment by vel8b8** [comment]
Doesn't happen on all custom item keys, just some. Might be that these key items are crafting items.

**Comment by ThyWoof** [comment]
Problem at the new recipes we create. All works if we comment out ItemCraftingContext.Load

**Comment by ThyWoof** [comment]
@ChrisPJohn , FYI

**Comment by ThyWoof** [comment]
fixed on 1.2.15.5
