### ISSUE TITLE
Clicking 'close' on the mod manager is still passed through to game UI

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#334]
A click on the Close button closes the mod manager and is then passed through to the game.

![image](https://user-images.githubusercontent.com/271656/147771055-0be80d82-8abd-4913-a21a-8d143c37f4f7.png)

**Comment by ThyWoof** [comment]
ESC to close is passed as well

**Comment by PhilPJL** [comment]
Fixed in ModApi
