### ISSUE TITLE
Witch with Burned curse does not get free Produce Flame cantrip

### ISSUE THREAD

**Issue by EnderWiggin** [ChrisPJohn/SolastaCommunityExpansion#395]
As title says - creating a Witch with Burned curse does not grant free Produce Flame cantrip. I can select it at character creation, as any other witch, but don't get it for free.

**Comment by ChrisPJohn** [comment]
While testing for our latest release (now on Nexus Mods), I tried making a Witch with Burned and I did get the Produce Flame cantrip. Does it work for you on the latest version (1.2.15.7)? If not can you share the list of mods you have installed (and what version)?

**Comment by EnderWiggin** [comment]
Yes, on current (1.2.15.7) version it works fine.
