### ISSUE TITLE
Witch spells available by default on other classes surprised users

### ISSUE THREAD

**Issue by ChrisPJohn** [ChrisPJohn/SolastaCommunityExpansion#420]
This is different from how other features work. We should have a minimum spell list set (this is what spell lists they default to on- which for the new Witch spells should just be Witch) and then suggested lists which is what spell lists they are intended to be on.

**Comment by ThyWoof** [comment]
I’ll handle it

**Comment by ThyWoof** [comment]
Implemented 3 possible sets on mod UI:

. All spells
. Minimum set
. Suggested set

Spell UI should also warn about higher level spells and level 20.

**Comment by ThyWoof** [comment]
Default is minimum set

**Comment by ChrisPJohn** [comment]
I believe this was fixed with #433.
