### ISSUE TITLE
Spell tooltips need to be set

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#431]
For example Bazou's 'Protect Threshold' which is base on 'Spike Growth'

![image](https://user-images.githubusercontent.com/271656/148700187-a9ffabbe-3e43-437e-a8e3-6fece4db4ef7.png)

**Comment by DubhHerder** [comment]
I guess you'd need to create a new effect proxy with a different title as the tooltip would be working off the proxy definition

petal storm uses a new effect proxy so if it doesnt have that issue, then it's definitely the proxy

**Comment by PhilPJL** [comment]
Fix for Protect Threshold.
