### ISSUE TITLE
increasing battle speed also increases the cutscene dialogue speed

### ISSUE THREAD

**Issue by ChrisPJohn** [ChrisPJohn/SolastaCommunityExpansion#453]
from GeneralJah215 on NexusMods

When I increase the game speed it messed up the story dialogue.  They speak the same speed but the back and forth cycles super fast so you don't hear it all and have to go back to the journal to re-read it.

I know this was supposed to be fixed in an earlier release but it is still happening in 1.2.15.6

**Comment by ThyWoof** [comment]
possible fix here: https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/462

**Comment by ThyWoof** [comment]
Imp has been checking this and we have considered removing this feature as it never worked as intended. What is your take @ChrisPJohn ?

**Comment by ThyWoof** [comment]
This feature never worked as intended and got removed from beta.
