### ISSUE TITLE
Hide items in fog of war

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#472]
If I mouse over, or press ALT various items become visible

![image](https://user-images.githubusercontent.com/271656/149414522-b73a3191-294c-4f0e-83da-be011e80b7a6.png)

Have an option to disable this.

**Comment by ThyWoof** [comment]
I'm researching this one. So far found out we can trap WorldGadget.SetHighlightVisibility(). We can use the VisibilityService and check the visited cells collection to change this method behavior.

**Comment by ThyWoof** [comment]
https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/474
