### ISSUE TITLE
[Character Creation] Thug

### ISSUE THREAD

**Issue by FelipeRenault** [ChrisPJohn/SolastaCommunityExpansion#593]
When creating a Rogue and looking into the subclasses, the description for Thug is not being loaded properly

![image](https://user-images.githubusercontent.com/40004649/151733645-525c32f5-1089-4955-b558-1343b81218f3.png)

**Comment by ThyWoof** [comment]
fixed on 1.2.15.8 to be released today or tomorrow top.

![image](https://user-images.githubusercontent.com/13087646/151733997-56053a29-582d-4ef5-98cb-bb41806420e2.png)
