### ISSUE TITLE
From Nexus: Livewood club/staff issues

### ISSUE THREAD

**Issue by ChrisPJohn** [ChrisPJohn/SolastaCommunityExpansion#703]
Wyldhunt
My druid started with a livewood club as a spell focus, but the club is marked as an arcane focus rather than a druidic focus.
I purchased a livewood staff instead (from Hugo Requer) since it's correctly marked as a druidic focus.
Unfortunately, the livewood staff equips to my amulet slot instead of my weapon slot.

**Comment by ThyWoof** [comment]
https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/725 fixes the slot types but clubs were already set to Druidic focus...

**Comment by ChrisPJohn** [comment]
> ![image](https://user-images.githubusercontent.com/13087646/153678620-ca95d384-c42a-4f56-981b-33111f95fc39.png) Druids don't start with any Livewood Club as far as I can tell.

It might be an option in the equipment configuration when selecting the class.

**Comment by ThyWoof** [comment]
They start with a default focus item. Not sure if we should change the basic equipment definition there

**Comment by ChrisPJohn** [comment]
It sounds like the reproducible issue is fixed. I'm marking this as fixed here (and will mark nexus fixed with the next release).

**Comment by MrSmite** [comment]
> Druids don't start with any Livewood Club as far as I can tell.


> It might be an option in the equipment configuration when selecting the class.

This is correct. You can edit your outfit and choose the club. The problem in 1.12.15.9 is the Druid can't cast certain spells because it says "you must wear or equip a druid focus or component pouch".
