### ISSUE TITLE
Modify progression

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#71]
From @czartchonn.  "Any chance for a option where you can slow down the xp you get? Hate it when you reach the cap early in a game and it adds difficulty too. Maybe a slider or an option for 75% to 50% received.".

I suggest a slider to alter XP received from say 50% to 200% of normal.
I'm happy to have a go at that.  Seems easy enough :)

**Comment by Czartchonn** [comment]
I always try to find something to slow down progression in most RPG. Almost all suffer from hitting the level cap far too early - making the game a breeze plus taking out the fun of progression. Hope it is easy to do :)

**Comment by ThyWoof** [comment]
@PhilPJL , what should be fairly easy to do is add a percentage slider and patch the method that grants experience and change result to be original exp * multiplier.

**Comment by ThyWoof** [comment]
I believe this should go under House Rules. Agree @ChrisPJohn ?

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/141490830-9a4b0fdb-0565-4f7e-a6fc-cff8f39b07eb.png)

**Comment by ThyWoof** [comment]
pushed. put under Tools as we already deal with exp. there.

**Comment by PhilPJL** [comment]
Hey I was going to do that :(

Anyway check out https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/ScaleExperienceReceived/SolastaCommunityExpansion/Patches/SrdAndHouseRulesContext/GrantExperienceExecutePatcher.cs

**Comment by PhilPJL** [comment]
Shouldn't have gone for a bike ride.

**Comment by ThyWoof** [comment]
Glad you are back riding 😜

**Comment by ThyWoof** [comment]
Will change to your math round fix

**Comment by PhilPJL** [comment]
It's not so easy after all because of FunctorGrantExperience which can grant enough XP to move all characters up to a specific level.  We need to disable scaling in that scenario, but a simple flag set on Prefix and reset on Postfix doesn't work because the functor logic is async.  Ideas?

**Comment by ChrisPJohn** [comment]
I believe this is done and in the released build, so closing the request.
