### ISSUE TITLE
From Nexus: Minor Lifesteal Does Not Provide Temp HP

### ISSUE THREAD

**Issue by ChrisPJohn** [ChrisPJohn/SolastaCommunityExpansion#717]
flerpidoodle
The description of minor lifesteal says it grants the stolen health as temp HP to the caster; in reality, it heals the caster. This might just be a documentation bug.

**Comment by mattelkinsTC** [comment]
Is the desired behavior to heal or to grant temp HP? I'm considering dipping a toe into helping out, if I can find the time. Not sure whether to patch the spell description or the spell.

**Comment by ChrisPJohn** [comment]
I think the original idea was to have it grant temp HP, but there were implementation issues with that. @RealBazou might have more information.
