### ISSUE TITLE
Forced level ups

### ISSUE THREAD

**Issue by Czartchonn** [ChrisPJohn/SolastaCommunityExpansion#90]
Cudos for making the slower progression. It really adds a lot when I play. There are some places however where a level up seems to be forced. In the beginning where you automatically get to be level 2 (not an issue). But then again in The Dark Castle you suddenly get enough xp to be level 5. So I got a few thousand xp being only level 4 there. Any way that could be tweaked in some way? As in not exist at all? It kind of defeats the purpose of slower progression if you are forced to level up in some places. 

Not a big deal, but would mention it. There may be others like me out there ;)

**Comment by ThyWoof** [comment]
We haven’t checked the entire gameplay but we know for sure the game won’t advance if you don’t level up to 2 in the very beginning. It might be doable if no other quests put a condition on party level.

**Comment by Czartchonn** [comment]
Don't know if it helps, but it happens fight after you enter the map where the defiler resides. The Gem Quest advances and you are hit with a level up.

**Comment by ThyWoof** [comment]
Please share a save before it happens so we can better understand and debug

**Comment by Czartchonn** [comment]
https://easyupload.io/na5yzj

Just enter the transition and the levelup occurs :)

**Comment by PhilPJL** [comment]
I can confirm that level up to 2 is required or you're stuck.
@Czartchonn I downloaded your 'adventuring.sav' but it never loads for me so can't test it.
A quick fix is to add a check box to enable/disable scaling level up requests, with a suitable note about "make sure you disable this before meeting Carran ... etc".

**Comment by Czartchonn** [comment]
Sure can do. But will take a while unfortunately. Will do it tomorrow afternoon give or take a few hours. Thanks for looking into it :)

**Comment by Czartchonn** [comment]
https://easyupload.io/2sscvc

Uploaded savegame packed with Winzip

**Comment by PhilPJL** [comment]
@Czartchonn Unfortunately that doesn't work either.  The .sav seems to be corrupted in some way. 

However, try copying the .dll here into your mod folder and see if that fixes your issue.  This will scale all level ups except for the one to L2 after the first legacy council meeting. This is a debug

[SolastaCommunityExpansion.zip](https://github.com/ChrisPJohn/SolastaCommunityExpansion/files/7540494/SolastaCommunityExpansion.zip)

**Comment by Czartchonn** [comment]
Hmm. Maybe it is some of my other mods that prevents you from loading the game. Will test it tomorrow - pretty busy at work, so no time for gaming at the moment. Thanks again :)

**Comment by PhilPJL** [comment]
ah ok.  Which other mods to you have?

**Comment by Czartchonn** [comment]
Solasta Extra Content and it's requirements. Plus FaceUnlocker

**Comment by PhilPJL** [comment]
Thanks, I was able to load your save with those mods and  I can confirm the updated code works.  After entering the transition with the experience multiplier set to 50% the characters all receive 959xp and still require another 959xp to level up.
![image](https://user-images.githubusercontent.com/271656/141994713-87f0df52-cdc9-4ba2-967a-410fccc0ae4f.png)

**Comment by Czartchonn** [comment]
Great! Hope I will have some time to play this weekend. You guys are great!

**Comment by PhilPJL** [comment]
Hmmm, maybe I didn't give you the correct .dll.  Tested it again, works for me with your save file
[SolastaCommunityExpansion.zip](https://github.com/ChrisPJohn/SolastaCommunityExpansion/files/7563883/SolastaCommunityExpansion.zip).
You need to unzip the .dll and paste it in the SolastaCommunityExpansion mod folder.  Delete that .cache file as well just to be sure.
![image](https://user-images.githubusercontent.com/271656/142444390-fcc45290-9a62-4dec-8cf1-0f62f0846618.png)

**Comment by ThyWoof** [comment]
@Czartchonn , what is the latest here?

**Comment by Czartchonn** [comment]
Latest file works like it should 👍
