### ISSUE TITLE
Level 20 BUG: Barbarian Primal Champion

### ISSUE THREAD

**Issue by ThyWoof** [ChrisPJohn/SolastaCommunityExpansion#94]
It has been reported Barb Primal Champion isn't working. As I wrote this code and not my forte in Solasta, big chance it's indeed not working... @ChrisPJohn , it should be an easy fix for you.

**Comment by CEDSS** [comment]
In the classes PrimalChampionConstitutionModifierBuilder.cs and PrimalChampionStrengthModifierBuilder.cs

15th line reads:
Definition.SetModifierType2(FeatureDefinitionAttributeModifier.AttributeModifierOperation.AddAbilityScoreBonus);

I changed it to:
Definition.SetModifierType2(FeatureDefinitionAttributeModifier.AttributeModifierOperation.Additive);

Made a new test barbarian character after compiling with that change, and it seems to be working now, it just won't increase the stats past their current maximums like Primal Champion does in the tabletop.

Tested the leveling up process exclusively in the main menu before and after making any changes, I don't know if anything changes while testing in an actual ongoing game. The stat increases showed up both in the level-up screen for level 20, and in the "Inspect" menu after having leveled up to 20.

**Comment by DubhHerder** [comment]
I think that an alternative approach would be to add a FeatureDefinitionPower similar to PowerFunctionManualBodilyWealth and PowerFunctionManualGainfulExercise as this would allow for an increase in both current and maximum ability score values

Using an effectform similar to 

        "$id": "2",
        "$type": "EffectForm, Assembly-CSharp",
        "formType": "Alteration",
        "levelMultiplier": 1,
        "createdByCharacter": true,
        "alterationForm": {
          "$id": "3",
          "$type": "AlterationForm, Assembly-CSharp",
          "alterationType": "AbilityScoreIncrease",
          "abilityScore": "Constitution",
          "valueIncrease": 4,
          "maximumIncrease": 4,
          "feastDurationHours": 1
        },


      {
        "$id": "2",
        "$type": "EffectForm, Assembly-CSharp",
        "formType": "Alteration",
        "levelMultiplier": 1,
        "createdByCharacter": true,
        "alterationForm": {
          "$id": "3",
          "$type": "AlterationForm, Assembly-CSharp",
          "alterationType": "AbilityScoreIncrease",
          "abilityScore": "Strength",
          "valueIncrease": 4,
          "maximumIncrease": 4,
          "feastDurationHours": 1
        },

**Comment by DubhHerder** [comment]
As noted, the above fix does not resolve the issue as the ability score increases are still at capped at 20. The issue should remain open until that feature is also implemented. The alternative solution i suggested above is how the base game increases the ability score caps.

**Comment by ChrisPJohn** [comment]
The issue is still open, that was an auto generated message from GitHub when I linked the pull to the issue. I don't like GitHub's assumption that an issue will always be solved by a linked pull request. Some issues take more than one pull to resolve.

**Comment by DubhHerder** [comment]
Here's a suggested solution for reference and comments:

```
     EffectDescriptionBuilder Effect_PrimalChampionBuilder = new EffectDescriptionBuilder();
            Effect_PrimalChampionBuilder.SetDurationData
                (
                RuleDefinitions.DurationType.Permanent, 
                1, 
                RuleDefinitions.TurnOccurenceType.EndOfTurn
                );
            Effect_PrimalChampionBuilder.SetTargetingData
                (
                RuleDefinitions.Side.Ally,
                RuleDefinitions.RangeType.Self,
                1, 
                RuleDefinitions.TargetType.Self, 
                1, 
                1, 
                ActionDefinitions.ItemSelectionType.Equiped
                );
            Effect_PrimalChampionBuilder.AddEffectForm
                (
                new EffectFormBuilder().SetAlterationAbilityScore
                    (
                    AttributeDefinitions.Strength,
                    4,
                    4
                    )
                    .Build()
                );
            Effect_PrimalChampionBuilder.AddEffectForm
                (
                new EffectFormBuilder().SetAlterationAbilityScore
                    (
                    AttributeDefinitions.Constitution,
                    4,
                    4
                    )
                    .Build()
                 );
            EffectDescription Effect_PrimalChampion = Effect_PrimalChampionBuilder.Build();


            var PrimalChampionBuilder = new FeatureDefinitionPowerBuilder(
                        "DH_PrimalChampion" ,
                        GuidHelper.Create(SignatureSpell_BASE_GUID, "DH_PrimalChampion").ToString(),
                        1,
                        RuleDefinitions.UsesDetermination.Fixed,
                        AttributeDefinitions.Charisma,
                        RuleDefinitions.ActivationTime.Permanent,
                        1,
                        RuleDefinitions.RechargeRate.LongRest,
                        false,
                        false,
                        AttributeDefinitions.Charisma,
                        Effect_PrimalChampion,
                       new GuiPresentationBuilder(
                            "Subclass/&PrimalChampionDescription",
                            "Subclass/&PrimalChampionTitle").Build(),
                        true);
            FeatureDefinitionPower PrimalChampion = PrimalChampionBuilder.AddToDB();



            var Barbarian = DatabaseHelper.CharacterClassDefinitions.Barbarian;
            Barbarian.FeatureUnlocks.Add(new FeatureUnlockByLevel(PrimalChampion, 20));
```

**Comment by ChrisPJohn** [comment]
I have an idea on custom defined features that would let us avoid the power for this. I'll try to get a prototype pull this week.

**Comment by DubhHerder** [comment]
Examples of the custom defined features would be interesting to see. 

The base game uses powers like PowerFunctionManualBodilyWealth and PowerFunctionManualGainfulExercise to implement very similar features so could you expand on the reason to avoid using powers for this?

**Comment by ChrisPJohn** [comment]
This is supposed to be something they get once at level up. A power would mean they need to go activate it after level up to get the benefit. Also if it recharges (like you have it set to do on a long rest), then the player could activate the power multiple times for a huge benefit.

**Comment by DubhHerder** [comment]
Yes, the feature is granted at level up. The base game and tinkerer mode also grants powers at level up (paladins aura's and tinkerer's flash of genius etc) which also use permanent activation, applying it automatically and so do not require manual activation. I don't think permanently activated powers can be manually activated from my experience playing.

For the image you can see that the power is applied but not power button is visible for manual activation, the image is after a long rest so it was only applied at the start of the dungeon on level up and not reapplied a second time after a long rest. 

![image](https://user-images.githubusercontent.com/83278737/147651106-4dbe65fb-5241-42e5-80b7-37a788fb370f.png)

**Comment by ChrisPJohn** [comment]
My bad I was skimming the code and say the power and long rest recharge, but missed the permament.

What happens if the hero dies and gets resurrected? Or if the hero travels between maps?

**Comment by DubhHerder** [comment]
I havent tested those scenarios, but will do so and update.

**Comment by DubhHerder** [comment]
You're right, those situations make it clear the power is not suitable. it stacks the boost when being revived or switching maps. thanks for the help.

**Comment by ChrisPJohn** [comment]
If we can just apply the effect you've defined once though, it should work. I have an idea for a custom feature definition that would support doing that, hopefully I'll get a chance soon to prototype.
