### ISSUE TITLE
Purple Dragon Knight Subclass

### ISSUE THREAD

**Issue by ThyWoof** [ChrisPJohn/SolastaCommunityExpansion#97]
get proper authorization from https://github.com/Mathih13/SolastaPurpleDragonKnightFighterSubclass to bring here.

**Comment by DubhHerder** [comment]
I'd suggest that if the subclass is incorporated that the references in the code and in game text to non SRD terminology be changed first. If altering the code is undesirable then change the in game text at least.

I believe the Nexus mods version v1.0.1 has done so but the GitHub v1.0.0 source code and release has not been updated.

For reference
https://www.nexusmods.com/solastacrownofthemagister/mods/89

**Comment by ThyWoof** [comment]
We can grab the translations from nexus

**Comment by ThyWoof** [comment]
In 1.2.15
